name: catalogs
channels:
 - conda-forge
 - pyviz
dependencies:
 - python=3.10*
 - s3fs
 - dask
 - xoak
 - xarray
 - numpy
 - intake
 - intake-xarray=0.6.1
 - intake-geopandas
 - intake-esm
 - hvplot
 - fsspec
 - intake-xarray
 - pyyaml
 - nbsphinx
 - pandoc
 - ipython
 - ipykernel=6.17.1
 - bokeh=2.4.3
 - geoviews
 - cartopy
 - itables
 - seaborn
 - tqdm
 - matplotlib
 - gcsfs
 - cfgrib
 - pystac-client
 - pip:
   - sphinx-pangeo-theme
   - furo
