name: catalogs
channels:
 - conda-forge
 - pyviz
dependencies:
 - python=3.8*
 - s3fs
 - dask
 - xoak
 - xarray
 - numpy
 - intake
 - intake-xarray
 - intake-geopandas
 - hvplot
 - fsspec
 - intake-xarray
 - pyyaml
 - nbsite
 - jupyter-panel-proxy
 - jupyter_contrib_nbextensions
 - jupyter_nbextensions_configurator
 - sphinx_holoviz_theme
